services:
  app:
    container_name: sample-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"